### ISSUE TITLE
Auto layout warnings

### ISSUE THREAD

**Issue by lorlab** [algal/UICVVariableHeightiOS8#1]
Hi. This seems to work but I get lots of "Unable to simultaneously satisfy constraints" warnings in the console... 
iOS 8.3, XCode 6.3.

**Comment by algal** [comment]
Thank you for this note!

I'm seeing the same thing. I will have a look at it. I have resolved this issue before, but I don't remember how, and I'd like to document it properly.

FWIW, the WWDC 2014 talk on Advanced Collection Views refers to an Apple sample app, based loosely on the iTunes Connect app, and this app includes a fix for this issue. But I remember it was a bit of a mess. There was a preprocessor macro to solve it different only on iOS7 vs iOS8. And the comments in the code mentioned a bug in UIKit. So it may be there's no clean answer.

**Comment by algal** [comment]
You can avoid this warning by changing the "dummy" height that's used for the sizing calculation from 0 (which is excessively small) to 30000 (which is excessively tall). I suspect this difference is because of the higher priority of the compression-resistance vs content-hugging layout constraints, but tbh I'm not sure.

I also suspect this warning is basically meaningless because it only appears once and does not seem to result in any layout errors. I think it's a result of some subtlety in how the collection view does its initial layout.

I'd like to understand it fall fully but not today. The new commit fixes it.
